### ISSUE TITLE
Error: "env: node\r: No such file or directory" when using aemsync v 0.7.0 on OSX

### ISSUE THREAD

**Issue by nicky** [gavoja/aemsync#10]
Hello,

Since upgrading to aemsync 0.7.0 this week I can't get it to run on OSX 10.10.3. I try to run:
`aemsync -t http://admin:admin@localhost:4502 -w ~/workspace/my_project`

And get error:
`env: node\r: No such file or directory`

I tried running dos2unix on `aemsync.js` suspecting a file ending error but couldn't get that to work either.

But uninstalling and reinstalling v 0.6.1 works fine:
`npm install aemsync@0.6.1 -g`

Apologies if this is not an error on aemsync side!

**Comment by gavoja** [comment]
Hi,

Apologies for the late reply. This appears to be caused by the incorrect line endings. I will fix this in the next release, which is coming next week.

Thanks,
Michal

**Comment by gavoja** [comment]
This should be fix in v0.7.1. Please test and reopen otherwise.
