### ISSUE TITLE
JSP pages sync not working

### ISSUE THREAD

**Issue by akshayashet** [gavoja/aemsync#16]
Hi,
I found one issue regarding aemsync. 

aemsync -t http://admin:admin@localhost:4503 -w /Users/ashet/Support/Projects/

All clientlib changes working fine. But any changes in JSP files sync not happening.

**Comment by gavoja** [comment]
Hi,

Can you please provide:
- System details (OS, Node.js version, aemsync version).
- The path to the JSP file that is not being picked up.
- The console output from aemsync when running in debug mode. To enable debug mode add `-d` at the end.

**Comment by akshayashet** [comment]
Hi gavoja,

System details (OS, Node.js version, aemsync version).

OS : 
![image](https://cloud.githubusercontent.com/assets/3539011/15015162/cb845e26-1227-11e6-8094-c8c3cee28af1.png)

Node.js version : v5.10.1

aemsync : 1.0.2.

The path to the JSP file that is not being picked up.
_/apps/support/components/feedback/feedback.jsp_


Console output:

Working dir: /Users/akshayashet/Support/Projects/cqsupport
        Targets: http://admin:admin@localhost:4503
       Interval: 300
        Exclude: 
  
Awaiting changes ...
Changed: /Users/akshayashet/Support/Projects/cqsupport/.git/index.lock
Changed: /Users/akshayashet/Support/Projects/cqsupport/.git/index.lock
Changed: /Users/akshayashet/Support/Projects/cqsupport/content/src/main/content/jcr_root/apps/support/components/feedback/feedback.jsp___jb_tmp___
Changed: /Users/akshayashet/Support/Projects/cqsupport/content/src/main/content/jcr_root/apps/support/components/feedback/feedback.jsp
Changed: /Users/akshayashet/Support/Projects/cqsupport/content/src/main/content/jcr_root/apps/support/components/feedback/feedback.jsp___jb_old___
DEL jcr_root/apps/support/components/feedback/feedback.jsp___jb_old___
ADD jcr_root/apps/support/components/feedback/feedback.jsp
DEL jcr_root/apps/support/components/feedback/feedback.jsp___jb_tmp___
  Creating archive: /var/folders/zl/kttycy5s5xsf4nb87bgvwvd40000gn/T/aemsync.zip
  Zipping: jcr_root/aemsync.txt
  Zipping: META-INF/vault/config.xml
  Zipping: META-INF/vault/definition/.content.xml
  Zipping: META-INF/vault/nodetypes.cnd
  Zipping: META-INF/vault/properties.xml
  Zipping: META-INF/vault/filter.xml
  <?xml version="1.0" encoding="UTF-8"?>
  <workspaceFilter version="1.0">
     <filter root="/apps/support/components/feedback/feedback.jsp___jb_old___" />
  </workspaceFilter>
  Changed: /Users/akshayashet/Support/Projects/cqsupport/content/src/main/content/jcr_root/.idea/atlassian-ide-plugin.xml
  Changed: /Users/akshayashet/Support/Projects/cqsupport/content/src/main/content/jcr_root/.idea/workspace.xml___jb_tmp___
  Posting...
  Changed: /Users/akshayashet/Support/Projects/cqsupport/content/src/main/content/jcr_root/.idea/workspace.xml___jb_tmp___
  Changed: /Users/akshayashet/Support/Projects/cqsupport/content/src/main/content/jcr_root/.idea/workspace.xml
  Changed: /Users/akshayashet/Support/Projects/cqsupport/content/src/main/content/jcr_root/.idea/workspace.xml___jb_old___
    Output from localhost:4503:
    <crx version="2.4.30" user="admin" workspace="crx.default">
      <request>
        <param name="file" value="aemsync.zip"/>
        <param name="force" value="true"/>
        <param name="install" value="true"/>
      </request>
      <response>
        <data>
          <package>
            <group></group>
            <name>aemsync</name>
            <version></version>
            <downloadName>aemsync.zip</downloadName>
            <size>3536</size>
            <created></created>
            <createdBy>AEM Synchronization Tool</createdBy>
            <lastModified></lastModified>
            <lastModifiedBy>null</lastModifiedBy>
            <lastUnpacked>Wed, 4 May 2016 08:29:11 +0530</lastUnpacked>
            <lastUnpackedBy>admin</lastUnpackedBy>
          </package>
          <log>
    Installing content...
    Collecting import information... 
    Installing node types... 
    - sling -&gt; http://sling.apache.org/jcr/sling/1.0
    - cq -&gt; http://www.day.com/jcr/cq/1.0
    - nt -&gt; http://www.jcp.org/jcr/nt/1.0
    - mix -&gt; http://www.jcp.org/jcr/mix/1.0
    - rep -&gt; internal
    - sling:Folder
    - sling:ResourceSuperType
    - cq:Component
    - cq:Dialog
    - cq:EditConfig
    - cq:EditListenersConfig
    - cq:InplaceEditingConfig
    - cq:Panel
    - cq:TabPanel
    - cq:Widget
    - cq:WidgetCollection
    - rep:RepoAccessControllable
    Installing privileges... 
    Importing content... 
    saving approx 0 nodes... 
    Package imported. 
    Package installed in 6ms.
          </log>
        </data>
        <status code="200">ok</status>
      </response>
    </crx>
  Deploying to [localhost:4503] in 83 ms at 2016-05-04T13:16:34.628Z: OK
Changed: /Users/akshayashet/Support/Projects/cqsupport/.git/index.lock
Changed: /Users/akshayashet/Support/Projects/cqsupport/.git/index.lock
Changed: /Users/akshayashet/Support/Projects/cqsupport/content/src/main/content/jcr_root/.idea/atlassian-ide-plugin.xml


Thanks

**Comment by gavoja** [comment]
I presume you use IntelliJ; it tends to create additional temporary files on save. Please check if the latest 1.1.0 version fixes your issue. If not, try increasing the interval to 600ms with `-i` option or filtering out `___jb_old___` and `___jb_tmp___` patterns with `-e`.

**Comment by gavoja** [comment]
Any update on this?

**Comment by akshayashet** [comment]
I am using Atom and Webstrom. But 1.1.0 release fixed the issue. Thanks a lot.
