### ISSUE TITLE
Aemsync throws exception after file is changed

### ISSUE THREAD

**Issue by viniciusdiogo** [gavoja/aemsync#20]
I installed the latest version (v.1.1.1) of aemsync and after starting aemsync, when I change a file to be synchronized, it throws the exception:
Note: In version (v1.1.0) occurs the same problem, but in (v1.0.2) worked.

```
Awaiting changes ...
/usr/local/lib/node_modules/aemsync/node_modules/simple-watcher/index.js:35
     callback(filePath)
     ^
TypeError: callback is not a function
   at /usr/local/lib/node_modules/aemsync/node_modules/simple-watcher/index.js:35:7
   at FSReqWrap.oncomplete (fs.js:82:15)
```
Environment: Node - v4.2.6 and Linux 4.4.0-34-generic #53-Ubuntu

**Comment by gavoja** [comment]
It would appear the fallback recursive watcher is buggy. To be confirmed and fixed.

**Comment by viniciusdiogo** [comment]
Hi, @gavoja the fix commit on https://github.com/gavoja/simple-watcher resolved this issue. Thanks.
