### ISSUE TITLE
Files with similar names are skipped

### ISSUE THREAD

**Issue by sovanyio** [gavoja/aemsync#22]
I'm trying to sync the following files:

styles.css
styles.min.css
styles.css.map

Default output is
```
ADD styles.min.css
ADD styles.css.map
Removing child: styles.css
ADD styles.css
```

I don't think the filename comparison at package.js:45 is appropriate, it should probably check whether or not the paths in question are paths vs individual files. I have just removed this check in my branch to get around this, but recognize that a proper comparison is a better solution.

**Comment by gavoja** [comment]
Can you please test with 2.0.0? I was not able to reproduce it. If you still encounter that bug, could you please run aemsync in debug mode (`-d`) and send me the output?

**Comment by gavoja** [comment]
Closing. If you believe this is still an issue, please send over a debug log.
