### ISSUE TITLE
use aemsync with Gulp/Webpack

### ISSUE THREAD

**Issue by zenithtekla** [gavoja/aemsync#25]
It is very promising to employ aemsync with Gulp/Webpack so that we can write complex Javascript files (ES6, TypeScript) and compile to ES5 compatible that can run on AEM and have the app work in conjunction with BrowserSync, Lite-Server and/or Hot-Module-Reloader(HMR).

The question here is **how to trigger the browser to automatically reload its tab current opening `localhost:4502` for every change made to the code base** (similar to BrowserSync). Any thoughts?

**Comment by gavoja** [comment]
The simplest way is to use WebSockets. I have implemented this in one of my side-projects:
https://github.com/gavoja/runna-webserver/

Basically the client code creates a WebSocket and listens for messages. The server side code sends the message through. Once the client code receives "reload" message, it reloads the browser.

**Comment by pristinetran** [comment]
Assume I'm running aemsync in 1 cli
If I open another cli and do the following, would it work?
`runa-webserver -p localhost:4502`

**Comment by pristinetran** [comment]
`runna-webserver -p 4502 -w /Users/admin/Dev/AEMcontainer/AEM/Author/crx-quickstart`

Running that, I have the following error:

Error: ENOENT: no such file or directory, stat 
'/Users/admin/Dev/IVC/secondProj/Users/admin/Dev/AEMcontainer/AEM/Author/crx-quickstart/crx/packmgr/service.jsp'
    at Error (native)

Replacing -w flag with this: `/Users/admin/Dev/IVC/secondProj/firstProj/ica/ui.apps/src/main/content/jcr_root`, I have the same error.

**Comment by gavoja** [comment]
The `runna-webserver` is just an HTTP server with auto reload functionality; it is not an AEM tool. I only suggested it as an example of how client side reload can be addressed.

In order to reload AEM page upon a sync, this is what you would have to do:
1. Start a server websocket and broadcast a message when aemsync completes.
2. Implement a client websocket on your website that would listen to the broadcast and reload a page when a message is received.

**Comment by pristinetran** [comment]
Thank you for your tips. I was wondering if I could implement those of your saying with `runna-webserver`.

**Comment by gavoja** [comment]
Not really, you still have to include something on your website to listen to messages.
