### ISSUE TITLE
Connection reset when trying to use SSL/TSL domain

### ISSUE THREAD

**Issue by c3ry5** [gavoja/aemsync#30]
When I try and use the sync with my aem instance that sits under SSL/TLS I get a ECONNRESET error.

`Deploying to [DOMAIN] in 104 ms at 2017-11-01T16:03:09.736Z: ECONNRESET`

**Comment by schoudry** [comment]
+1

**Comment by gavoja** [comment]
Version 4 uses node-fetch for requests. Hopefully the SSL should work. Could you please test?

**Comment by gavoja** [comment]
Closing due to lack of interest.
