### ISSUE TITLE
Plugin adds but does not push .map files to server

### ISSUE THREAD

**Issue by ChristophWuerzlhuber** [gavoja/aemsync#31]
I'm using aemsync with a webpack configuration, where I'm pushing bundled css and js files to the server. I'm also generating sourcemaps for this files. 
According to the console output the .map files are added to the package, but when I download the pushed zip file from the servers crx package manager, the .map files are not included in the package.

**Comment by gavoja** [comment]
I have no issues synchronising `.map` files. Can you please provide steps to reproduce the issue? What is the path?

**Comment by gavoja** [comment]
Closing. If you still think this is an issue, please provide clear steps to reproduce.
