### ISSUE TITLE
Exclusion doesn't work on a path when directory starts with a dot symbol

### ISSUE THREAD

**Issue by qrwex** [gavoja/aemsync#32]
The problem is in a /src/watcher.js:16

The following code result is **false**:
`console.log(mm('users/example/directory/node_modules/.micromatch.DELETE/node_modules', ['**/example/directory/**']).length > 0);
`

Possible solution:
`if (exclude && mm([localPath], exclude, {dot: true}).length > 0) {`

**Comment by gavoja** [comment]
Should work with 3.0.0. Reopen otherwise.

**Comment by abmaonline** [comment]
The parameters for the micromatch call are not in the right order, fixed it in https://github.com/gavoja/aemsync/pull/37
