### ISSUE TITLE
Don't skip files in target folders

### ISSUE THREAD

**Issue by sovanyio** [gavoja/aemsync#35]
The sync should not ignore `*/target/*` files. Our build process only outputs to target and doesn't work with this package OOTB. There is mention here that it may be appropriate to remove here https://github.com/gavoja/aemsync/issues/8, if not removed, maybe it makes sense to expose the ability to include target via a switch?

**Comment by gavoja** [comment]
Target is ignored due to Maven/Java builds copying the entire `jcr_content` inside `target`, which majority of AEM projects use. Can you not simply use a different folder name in your build process?

**Comment by sovanyio** [comment]
Well I was hoping to use the same scripts for the maven build process with the developer build process. Since the outputs of the front end scripting are build artifacts, I think it is appropriate for them to be in target?

**Comment by easingthemes** [comment]
It's working fine if you remove `target` exclusion. 

And if someone need to exclude it, there is an option for that. 
So I think you should remove that hardcoded mach. 

Thanks.

**Comment by gavoja** [comment]
Do you use Maven? If so, can you try building a project while aemsync is running?

**Comment by easingthemes** [comment]
Maven build works fine while `aemsync` is running, and vice versa.

**Comment by easingthemes** [comment]
I changed that target regex
`const RE_TARGET_PATH = /^.*\/(targett|\..*)\/(.*\/)?jcr_root\/.*$/`
and using it for months like that without issues.

**Comment by gavoja** [comment]
Since version 4 the default exclude filter can be overridden. Please test your case.

**Comment by gavoja** [comment]
Outdated, closing.
