### ISSUE TITLE
Minimatch produce different regex compared to micromatch

### ISSUE THREAD

**Issue by magnli10** [gavoja/aemsync#42]
After updating from 3.0.1 to 3.0.2 I noticed the exclude filters were no longer working after micromatch was replaced. The two libraries yields very different output in certain cases, for example:
```
**/assets|**/assets/** 

micromatch => /^(?:(?:(?:(?!(?:\/|^)\.).)*?\/|)assets|(?:(?:(?!(?:\/|^)\.).)*?\/|)assets\/(?:(?!(?:\/|^)\.).)*?)$/
minimatch => /^(?:(?:(?!(?:\/|^)\.).)*?\/(?=.)assets\|[^\/]*?[^\/]*?\/assets\/(?:(?!(?:\/|^)\.).)*?)$/
```
when matched against `nettsider/components/foobar/assets/index.js` only micromatch gives a positive result.

**Comment by gavoja** [comment]
Version 4 uses globrex library. I used in in other projects and it proved to be solid. It supports extended globbing and has zero dependencies. Could you please test your case?

**Comment by gavoja** [comment]
Outdated, closing. Please reopen if reoccurs.
