### ISSUE TITLE
Not syncing content in aem archtype based project

### ISSUE THREAD

**Issue by patrickhousley** [gavoja/aemsync#51]
I have a few projects that were created from the [AEM Archtype Template](https://github.com/adobe/aem-project-archetype/tree/master/src/main/archetype/ui.frontend.general) and I cannot seem to get the content to sync using aemsync. The standard sync script is `"sync": "aemsync -d -p ../ui.apps/src/main/content",` which I think is part of the problem. Per [package.js#L44](https://github.com/gavoja/aemsync/blob/master/src/package.js#L44), if the local path to be synced does not include `jcr_root`, the path is ignored. However, changing the script to `"sync": "aemsync -d -p ../ui.apps/src/main/content/jcr_root/apps",` still does not work. I believe this is because the default path exclusion includes `**/jcr_root/*` [here](https://github.com/gavoja/aemsync/blob/master/src/defaults.js#L5).

If I am reading the code correctly, and forgive me if I am not here, the local path must include `jcr_root` but such a path is excluded by default. I was able to work around this by specifying more of the path I want synced: `aemsync -d -p ../ui.apps/src/main/content/jcr_root/apps/brandA`

Is this the way the code is meant to work? Does it require a deeper path like I found or is there room for or maybe a need for allowing the syncing of the `/jcr_root/` folder or maybe `/jcr_root/apps/`? I have also found through troubleshooting this that some console logging for the user might be needed to help people uncover why their content is not syncing.

**Comment by gavoja** [comment]
This works as intended and perhaps I should have documented it better. Please note that the push does a complete override rather than a merge. For this reason it is allowed from the second level nodes only (e.g. `/apps/my-app`). This is a security check to avoid accidentally overwriting `/apps`, `/libs` or any other first level node in AEM, which could corrupt it.

**Comment by patrickhousley** [comment]
Thanks for the information @gavoja
