### ISSUE TITLE
RE_SAFE_PATH test fails

### ISSUE THREAD

**Issue by AxelHo** [gavoja/aemsync#8]
i changed an html sightly file, the watcher detects it correctly but the RE_SAFE_PATH test fails.
if (!RE_SAFE_PATH.test(item)) {
return;
}
Maybe i used the wrong path?
Can you help me out, where exactly set the path too.

**Comment by gavoja** [comment]
Could you please tell me what is the value of the `item` for which the test fails? 

The file to be pushed:

1. Must be two levels below `jcr_root` (which prevents form accidentally deleting first level nodes such as `apps` or `etc`).
2. Must not be inside `target` folder (although I reckon this could be removed).
3. Must not be inside a hidden folder (which name starts with a dot).

**Comment by AxelHo** [comment]
this fix solved the problem thanks a lot
